const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

export function createApiKeyFeature({api,escapeHtml,toast}){
  let keys=[],activeIndex=0;
  const sync=()=>{keys=$$('[data-gemini-api-key]').map(input=>input.value);};
  const render=()=>{
    $('#geminiApiKeyCount').textContent=keys.length?`${keys.length} key · hiện tại #${activeIndex+1}`:'0 key';
    const start=$('#geminiStartKey');if(start){start.innerHTML=keys.map((_,index)=>`<option value="${index}">Key #${index+1}</option>`).join('');start.value=String(Math.min(activeIndex,Math.max(0,keys.length-1)));start.disabled=!keys.length;}
    $('#geminiApiKeyList').innerHTML=keys.map((key,index)=>`<div class="api-key-row"><span>${index+1}</span><input type="password" value="${escapeHtml(key)}" data-gemini-api-key autocomplete="off" spellcheck="false" aria-label="Gemini API key ${index+1}"><button type="button" class="secondary" data-toggle-api-key>Hiện</button><button type="button" class="secondary" data-test-api-key>Kiểm tra</button><button type="button" class="api-key-remove" data-remove-api-key aria-label="Xóa API key ${index+1}">Xóa</button><small class="api-key-test-status" data-api-key-test-status></small></div>`).join('')||'<div class="api-key-empty">Chưa có API key. Hãy thêm key để sử dụng Gemini API.</div>';
    $$('[data-toggle-api-key]').forEach(button=>button.onclick=()=>{const input=button.parentElement.querySelector('input'),hidden=input.type==='password';input.type=hidden?'text':'password';button.textContent=hidden?'Ẩn':'Hiện';});
    $$('[data-test-api-key]').forEach(button=>button.onclick=()=>testOne(button));
    $$('[data-remove-api-key]').forEach((button,index)=>button.onclick=()=>{sync();keys.splice(index,1);render();});
  };
  const load=async()=>{try{const data=await api('/api/gemini-api-keys');keys=data.keys;activeIndex=Number(data.active_index)||0;render();}catch(error){toast(error.message);}};
  const selectActive=async()=>{const select=$('#geminiStartKey'),previous=activeIndex;select.disabled=true;try{const data=await api('/api/gemini-api-keys/active',{method:'POST',body:JSON.stringify({active_index:Number(select.value)})});activeIndex=Number(data.active_index)||0;render();toast(`Lần chạy sau sẽ bắt đầu từ key #${activeIndex+1}`);}catch(error){activeIndex=previous;render();toast(error.message);}finally{select.disabled=!keys.length;}};
  const save=async()=>{sync();const button=$('#saveGeminiApiKeys');button.disabled=true;try{const data=await api('/api/gemini-api-keys',{method:'POST',body:JSON.stringify({keys})});keys=data.keys;activeIndex=Number(data.active_index)||0;render();toast(`Đã lưu ${data.count} Gemini API key`);}catch(error){toast(error.message);}finally{button.disabled=false;}};
  const testOne=async(button)=>{const key=button.parentElement.querySelector('[data-gemini-api-key]').value.trim(),status=button.parentElement.querySelector('[data-api-key-test-status]');if(!key){status.className='api-key-test-status error';status.textContent='LỖI · Key đang trống';return false;}button.disabled=true;button.textContent='Đang kiểm tra…';try{const data=await api('/api/gemini-api-keys/test',{method:'POST',body:JSON.stringify({key})});status.className=`api-key-test-status ${data.ok?'success':'error'}`;status.textContent=`${data.code} · ${data.message} · ${data.model}`;return data.ok;}catch(error){status.className='api-key-test-status error';status.textContent=`LỖI · ${error.message}`;return false;}finally{button.disabled=false;button.textContent='Kiểm tra';}};
  const testAll=async()=>{const buttons=$$('[data-test-api-key]'),batch=$('#testAllGeminiApiKeys');if(!buttons.length)return toast('Chưa có API key để kiểm tra');batch.disabled=true;batch.textContent=`Đang kiểm tra 0/${buttons.length}…`;let passed=0;try{for(let index=0;index<buttons.length;index++){batch.textContent=`Đang kiểm tra ${index+1}/${buttons.length}…`;if(await testOne(buttons[index]))passed++;}toast(`Kiểm tra xong: ${passed} hoạt động, ${buttons.length-passed} lỗi`);}finally{batch.disabled=false;batch.textContent='Kiểm tra tất cả';}};
  const add=()=>{sync();keys.push('');render();const inputs=$$('[data-gemini-api-key]');inputs[inputs.length-1]?.focus();};
  const bind=()=>{if(!$('#geminiStartKey'))$('#addGeminiApiKey').insertAdjacentHTML('afterend','<label class="api-key-start"><span>Bắt đầu từ</span><select id="geminiStartKey" aria-label="Chọn API key bắt đầu"></select></label>');if(!$('#testAllGeminiApiKeys'))$('#saveGeminiApiKeys').insertAdjacentHTML('beforebegin','<button class="secondary" id="testAllGeminiApiKeys" type="button">Kiểm tra tất cả</button>');$('#geminiStartKey').onchange=selectActive;$('#testAllGeminiApiKeys').onclick=testAll;$('#addGeminiApiKey').onclick=add;$('#saveGeminiApiKeys').onclick=save;const hint=$('#geminiApiKeyManager .api-key-head small');if(hint)hint.textContent='Mỗi key được lưu trên một dòng trong data/apikeys.txt.';};
  return {bind,load};
}
