const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

export function createChapterImportFeature({api,escapeHtml,getProject,loadChapters,openChapter,toast}) {
  let preview=null;
  const render=()=>{
    if(!preview)return;
    const from=Number($('#chapterImportFrom').value),to=Number($('#chapterImportTo').value);
    const volume=Number($('#chapterImportVolume').value),start=Number($('#chapterImportStart').value);
    const confidence={high:'Cao',medium:'Khá',manual:'Cần kiểm tra'}[preview.confidence]||'Cần kiểm tra';
    $('#chapterImportSuggestion').innerHTML=preview.no_new?`<strong>Chưa thấy chương mới rõ ràng</strong><span>Đã tìm thấy ${preview.anchors} điểm neo. Hãy chọn range thủ công nếu EPUB có cấu trúc khác.</span>`:`<strong>Đề xuất · độ tin cậy ${confidence}</strong><span>${preview.anchors} chương trùng dùng làm điểm neo · nguồn ${from}–${to} → v${volume}_c${start}…</span>`;
    $('#chapterImportRows').innerHTML=preview.chapters.map(chapter=>{const inRange=chapter.source_index>=from&&chapter.source_index<=to,target=start+chapter.source_index-from,checked=inRange&&chapter.selected?'checked':'';return `<tr class="${inRange?'':'outside-range'}"><td><input type="checkbox" data-import-source="${chapter.source_index}" ${checked} ${inRange?'':'disabled'}></td><td><strong>${chapter.source_index}</strong><span>${escapeHtml(chapter.title)}</span></td><td><code>v${volume}_c${target}_s*.md</code></td><td>${chapter.match?`<b>${chapter.match}</b><small>${Math.round(chapter.match_score*100)}%</small>`:'—'}</td></tr>`;}).join('');
    $$('[data-import-source]').forEach(input=>input.onchange=()=>{const chapter=preview.chapters.find(item=>item.source_index===Number(input.dataset.importSource));if(chapter)chapter.selected=input.checked;});
  };
  const open=()=>{if(!getProject())return toast('Hãy chọn truyện trước');preview=null;$('#chapterImportFile').value='';$('#chapterImportPreview').classList.remove('open');$('#analyzeChapterImport').style.display='';$('#confirmChapterImport').style.display='none';$('#chapterImportModal').classList.add('open');};
  const updateRange=()=>{if(!preview)return;const from=Number($('#chapterImportFrom').value),to=Number($('#chapterImportTo').value);preview.chapters.forEach(chapter=>{chapter.selected=chapter.source_index>=from&&chapter.source_index<=to;});render();};
  const analyze=async()=>{const file=$('#chapterImportFile').files[0],limit=Number($('#chapterImportSegmentLimit').value),button=$('#analyzeChapterImport');if(!file)return toast('Hãy chọn file EPUB hoặc TXT');const format=file.name.toLowerCase().endsWith('.epub')?'epub':file.name.toLowerCase().endsWith('.txt')?'txt':'';if(!format)return toast('File phải có định dạng EPUB hoặc TXT');if(!Number.isInteger(limit)||limit<500||limit>50000)return toast('Giới hạn segment phải từ 500 đến 50.000');button.disabled=true;button.textContent='Đang tìm điểm neo…';try{const query=new URLSearchParams({project:getProject(),format,segment_limit:String(limit)});preview=await api('/api/chapters/import-preview?'+query,{method:'POST',headers:{'Content-Type':format==='epub'?'application/epub+zip':'text/plain;charset=utf-8'},body:file});$('#chapterImportFrom').value=preview.source_from;$('#chapterImportTo').value=preview.source_to;$('#chapterImportVolume').value=preview.target_volume;$('#chapterImportStart').value=preview.target_start;$('#chapterImportPreview').classList.add('open');button.style.display='none';$('#confirmChapterImport').style.display='';render();}catch(error){toast(error.message);}finally{button.disabled=false;button.textContent='Phân tích file';}};
  const confirmImport=async()=>{if(!preview)return;const button=$('#confirmChapterImport'),from=Number($('#chapterImportFrom').value),to=Number($('#chapterImportTo').value),volume=Number($('#chapterImportVolume').value),start=Number($('#chapterImportStart').value),selected=$$('[data-import-source]:checked').map(input=>Number(input.dataset.importSource));if(!Number.isInteger(from)||!Number.isInteger(to)||to<from||volume<0||start<0)return toast('Range hoặc chương đích không hợp lệ');if(!selected.length)return toast('Hãy chọn ít nhất một chương để nhập');button.disabled=true;button.textContent='Đang nhập…';try{const result=await api('/api/chapters/import-confirm?project='+encodeURIComponent(getProject()),{method:'POST',body:JSON.stringify({token:preview.token,source_from:from,source_to:to,target_volume:volume,target_start:start,selected,conflict:$('#chapterImportConflict').value})});$('#chapterImportModal').classList.remove('open');preview=null;await loadChapters();if(result.first_file)await openChapter(result.first_file);toast(`Đã thêm ${result.imported} chương${result.skipped?` · bỏ qua ${result.skipped} chương trùng`:''}${result.overwritten?` · ghi đè ${result.overwritten}`:''}`);}catch(error){toast(error.message);}finally{button.disabled=false;button.textContent='Nhập các chương đã chọn';}};
  const cancel=async()=>{const current=preview;preview=null;$('#chapterImportModal').classList.remove('open');if(current)try{await api('/api/chapters/import-cancel',{method:'POST',body:JSON.stringify({token:current.token})});}catch(_error){}};
  const bind=()=>{$('#addChaptersButton').onclick=open;$('#cancelChapterImport').onclick=cancel;$('#analyzeChapterImport').onclick=analyze;$('#confirmChapterImport').onclick=confirmImport;['chapterImportFrom','chapterImportTo'].forEach(id=>$(`#${id}`).oninput=updateRange);['chapterImportVolume','chapterImportStart'].forEach(id=>$(`#${id}`).oninput=render);};
  return {bind};
}
