const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

export function createSharingFeature({api,copyPlainText,escapeHtml,getChapters,getProject,openSettings,toast}) {
  let shares=[];
  const selectedChapters=()=>$$('[data-share-chapter]:checked').flatMap(input=>JSON.parse(input.dataset.shareFiles||'[]'));
  const groupedChapters=()=>{
    const groups=new Map();
    getChapters().filter(item=>item.translated).forEach(item=>{
      const match=String(item.name||'').match(/^v(\d+)_c(\d+)_s(\d+)\.md$/i),key=match?`v${Number(match[1])}_c${Number(match[2])}`:`file:${item.name}`;
      if(!groups.has(key))groups.set(key,{title:item.title||item.id,names:[],order:match?[Number(match[1]),Number(match[2])]:[Number.MAX_SAFE_INTEGER,item.name]});
      groups.get(key).names.push({name:item.name,segment:match?Number(match[3]):0});
    });
    return [...groups.values()].map(group=>({...group,names:group.names.sort((a,b)=>a.segment-b.segment).map(item=>item.name)})).sort((a,b)=>a.order[0]-b.order[0]||(typeof a.order[1]==='number'?a.order[1]-b.order[1]:String(a.order[1]).localeCompare(String(b.order[1]))));
  };
  const matchingDraft=()=>{const recipient=$('#shareRecipient').value.trim().toLocaleLowerCase(),title=($('#shareTitle').value.trim()||getProject()||'').toLocaleLowerCase();return [...shares].reverse().find(item=>recipient?String(item.recipient||'').trim().toLocaleLowerCase()===recipient:String(item.title||'').trim().toLocaleLowerCase()===title);};
  const updatePrimaryAction=()=>{if($('#createShare').dataset.loading==='true')return;const match=matchingDraft();$('#createShare').textContent=match?'Cập nhật bản share':'Tạo bản share';$('#createShare').dataset.matchedShare=match?.id||'';};
  const renderCatalog=()=>{const catalog=$('#sharedChapterCatalog');if(!catalog)return;catalog.innerHTML=shares.map(item=>`<section class="shared-catalog-group"><div class="shared-catalog-head"><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.recipient||'Không gắn người nhận')} · ${item.chapters?.length||0} chương</small></div><button type="button" data-close-share="${escapeHtml(item.id)}">Đóng share</button></div><div class="shared-catalog-list">${(item.chapters||[]).map(chapter=>`<div class="shared-catalog-row"><span>${escapeHtml(chapter.title||chapter.name)}</span><button type="button" data-remove-shared-chapter="${escapeHtml(chapter.name)}" data-share-id="${escapeHtml(item.id)}">Thu hồi</button></div>`).join('')||'<div class="memory-empty">Bản share chưa có chương.</div>'}</div></section>`).join('')||'<div class="memory-empty">Chưa có chương nào đang được chia sẻ.</div>';};
  const render=()=>{const project=getProject(),translated=groupedChapters();$('#shareTitle').placeholder=project||'Tên bản đọc';$('#shareChapterList').innerHTML=translated.map(item=>`<label class="share-chapter"><input type="checkbox" data-share-chapter data-share-files="${escapeHtml(JSON.stringify(item.names))}"><span>${escapeHtml(item.title)}${item.names.length>1?` <small>· ${item.names.length} phần</small>`:''}</span></label>`).join('')||'<div class="memory-empty">Chưa có chương đã dịch.</div>';$('#shareList').innerHTML=shares.map(item=>`<article class="share-item"><div class="share-item-head"><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.recipient||'Không gắn người nhận')} · ${item.chapters?.length||0} chương</small></div><small>${escapeHtml(String(item.expires_at||'').slice(0,10))}</small></div><div class="share-item-actions"><button class="secondary" type="button" data-copy-share="${escapeHtml(item.url||'')}" ${item.url?'':'disabled'}>Sao chép link</button><button class="primary" type="button" data-update-share="${escapeHtml(item.id)}">Cập nhật chương đã chọn</button></div></article>`).join('')||'<div class="memory-empty">Chưa tạo bản share nào cho truyện này.</div>';renderCatalog();updatePrimaryAction();};
  const load=async()=>{const project=getProject();if(!project){shares=[];render();return;}try{const data=await api('/api/shares?project='+encodeURIComponent(project));shares=data.items||[];render();}catch(error){shares=[];render();toast(error.message);}};
  const write=async(shareId='')=>{const project=getProject();if(!project)return toast('Hãy chọn một truyện trước');if($('#createShare').dataset.loading==='true')return;const chapters=selectedChapters();if(!chapters.length)return toast('Hãy chọn ít nhất một chương đã dịch');if(!shareId)shareId=matchingDraft()?.id||'';const existing=shares.find(item=>item.id===shareId),title=$('#shareTitle').value.trim()||existing?.title||project,recipient=$('#shareRecipient').value.trim()||existing?.recipient||'',button=$('#createShare');button.disabled=true;button.dataset.loading='true';button.setAttribute('aria-busy','true');button.classList.add('is-loading');button.textContent=shareId?'Đang cập nhật…':'Đang tạo share…';try{const data=await api('/api/shares?project='+encodeURIComponent(project),{method:'POST',body:JSON.stringify({share_id:shareId,title,recipient,expires_days:$('#shareExpiresDays').value,chapters})});shares=data.items||[];render();toast(shareId?'Đã cập nhật các chương lên R2':'Đã tạo bản share private');}catch(error){toast(error.message);}finally{button.disabled=false;button.dataset.loading='false';button.removeAttribute('aria-busy');button.classList.remove('is-loading');updatePrimaryAction();}};
  const change=async(action,shareId,chapter='')=>{const prompt=action==='close'?'Đóng bản share và xóa toàn bộ chương của nó khỏi R2?':'Thu hồi chương này khỏi bản share và R2?';if(!confirm(prompt))return;try{const data=await api('/api/shares?project='+encodeURIComponent(getProject()),{method:'POST',body:JSON.stringify({action,share_id:shareId,chapter})});shares=data.items||[];render();toast(action==='close'?'Đã đóng và thu hồi bản share':'Đã thu hồi chương khỏi R2');}catch(error){toast(error.message);}};
  const bind=()=>{$('#createShare').onclick=()=>write($('#createShare').dataset.matchedShare||'');['shareTitle','shareRecipient'].forEach(id=>$(`#${id}`).addEventListener('input',updatePrimaryAction));$('#toggleShareChapters').onclick=()=>{const boxes=$$('[data-share-chapter]'),select=boxes.some(box=>!box.checked);boxes.forEach(box=>box.checked=select);$('#toggleShareChapters').textContent=select?'Bỏ chọn tất cả':'Chọn tất cả';};$('#shareList').onclick=event=>{const update=event.target.closest('[data-update-share]');if(update)write(update.dataset.updateShare);const copy=event.target.closest('[data-copy-share]');if(copy&&copy.dataset.copyShare)copyPlainText(copy.dataset.copyShare);};$('#sharedChapterCatalog').onclick=event=>{const close=event.target.closest('[data-close-share]');if(close)return change('close',close.dataset.closeShare);const remove=event.target.closest('[data-remove-shared-chapter]');if(remove)change('remove_chapter',remove.dataset.shareId,remove.dataset.removeSharedChapter);};$('#openShareSettings').onclick=openSettings;};
  return {bind,load,render};
}
