const $ = (selector) => document.querySelector(selector);

export function createUpdateFeature({api,escapeHtml,hasUnsavedChanges,toast}){
  let available=null,whatsNew=null;
  const renderStatus=(data)=>{
    available=data.update_available&&data.download_ready?data:null;
    const current=`v${data.current_version}`;
    const version=$('#updateVersion'),status=$('#updateStatus'),button=$('#checkUpdate');
    if(version)version.textContent=data.latest_version&&String(data.latest_version)!==String(data.current_version)?`${current} → v${data.latest_version}`:current;
    if(status)status.textContent=data.error||data.message||(data.status==='up_to_date'?'Bạn đang dùng bản mới nhất.':data.status==='no_release'?'Chưa có bản phát hành mới.':'Sẵn sàng kiểm tra bản mới.');
    if(button){button.textContent=available?'Tải và cập nhật':'Kiểm tra cập nhật';button.classList.toggle('primary',Boolean(available));button.classList.toggle('secondary',!available);}
  };
  const load=async(check=false)=>{const button=$('#checkUpdate');if(check&&button){button.disabled=true;button.textContent='Đang kiểm tra…';}try{const data=await api('/api/update'+(check?'?check=1':''));renderStatus(data);if(check)toast(data.message||'Đã kiểm tra cập nhật');return data;}catch(error){const status=$('#updateStatus');if(status)status.textContent=error.message;if(check)toast(error.message);return null;}finally{if(button)button.disabled=false;}};
  const autoCheck=async()=>{const last=Number(localStorage.getItem('novel-update-check')||0);if(Date.now()-last<6*60*60*1000)return;localStorage.setItem('novel-update-check',String(Date.now()));try{renderStatus(await api('/api/update?check=1'));}catch(_error){}};
  const renderWhatsNew=(entry)=>{$('#whatsNewVersion').textContent=`v${entry.version}${entry.date?` · ${entry.date}`:''}`;$('#whatsNewTitle').textContent=entry.title||'Có gì mới?';$('#whatsNewSummary').textContent=entry.summary||'Ứng dụng đã được cập nhật lên phiên bản mới.';const highlights=Array.isArray(entry.highlights)?entry.highlights.filter(Boolean):[];$('#whatsNewList').innerHTML=highlights.length?highlights.map(item=>`<div class="whats-new-item"><span>✓</span><p>${escapeHtml(item)}</p></div>`).join(''):'<div class="whats-new-empty">Chưa có ghi chú chi tiết cho phiên bản này.</div>';};
  const loadWhatsNew=async(force=false)=>{try{const [update,notes,launcher]=await Promise.all([api('/api/update'),api('/release-notes.json'),api('/api/launcher')]),versions=Array.isArray(notes.versions)?notes.versions:[];const entry=versions.find(item=>String(item.version)===String(update.current_version))||{version:update.current_version,title:`Aiko App Translator ${update.current_version}`,summary:'Ứng dụng đã được cập nhật lên phiên bản mới.',highlights:[]};whatsNew=entry;renderWhatsNew(entry);const needsLauncher=Boolean(launcher.available&&!launcher.configured);$('#launcherOnboarding').hidden=!needsLauncher;const seen=localStorage.getItem('novel-whats-new-version');if(force||needsLauncher||seen!==String(entry.version)){$('#whatsNewModal').classList.add('open');requestAnimationFrame(()=>(needsLauncher?$('#openLauncherOnboarding'):$('#closeWhatsNew')).focus());}}catch(error){if(force)toast(error.message);}};
  const closeWhatsNew=()=>{if(whatsNew?.version)localStorage.setItem('novel-whats-new-version',String(whatsNew.version));$('#whatsNewModal').classList.remove('open');};
  const install=async()=>{if(hasUnsavedChanges())return toast('Hãy lưu thay đổi đang soạn trước khi cập nhật');if(!available)return load(true);if(!confirm(`Tải và cập nhật lên phiên bản ${available.latest_version}? App sẽ tự khởi động lại.`))return;const button=$('#checkUpdate');button.disabled=true;button.textContent='Đang tải bản cập nhật…';try{const result=await api('/api/update',{method:'POST',body:'{}'});$('#updateStatus').textContent=result.message;button.textContent='Đang khởi động lại…';toast(result.message);}catch(error){button.disabled=false;button.textContent='Tải và cập nhật';$('#updateStatus').textContent=error.message;toast(error.message);}};
  const openLauncher=async()=>{const button=$('#openLauncherOnboarding');button.disabled=true;button.textContent='Đang mở…';try{const result=await api('/api/launcher/open',{method:'POST',body:'{}'});$('#launcherOnboarding').hidden=true;toast(result.message);}catch(error){button.disabled=false;button.textContent='Mở launcher ngay';toast(error.message);}};
  const bind=()=>{const check=$('#checkUpdate'),notes=$('#showWhatsNew'),close=$('#closeWhatsNew'),launcher=$('#openLauncherOnboarding');if(check)check.onclick=()=>available?install():load(true);if(notes)notes.onclick=()=>loadWhatsNew(true);if(close)close.onclick=closeWhatsNew;if(launcher)launcher.onclick=openLauncher;};
  return {autoCheck,bind,closeWhatsNew,load,loadWhatsNew};
}
