const $ = (selector) => document.querySelector(selector);

export function createUpdateFeature({api,escapeHtml,hasUnsavedChanges,toast}){
  let available=null,whatsNew=null,pollTimer=null,installing=false;
  const formatBytes=(value)=>`${(Number(value||0)/1048576).toFixed(1)} MB`;
  const formatTime=(seconds)=>{const value=Math.max(0,Math.round(Number(seconds)||0));return value>=60?`${Math.floor(value/60)} phút ${value%60} giây`:`${value} giây`;};
  const resetProgress=()=>{const box=$('#updateProgress'),cancel=$('#cancelUpdate');if(box)box.hidden=true;if(cancel)cancel.hidden=true;};
  const renderStatus=(data)=>{
    available=data.update_available&&data.download_ready?data:null;
    const current=`v${data.current_version}`,version=$('#updateVersion'),status=$('#updateStatus'),button=$('#checkUpdate');
    if(version)version.textContent=data.latest_version&&String(data.latest_version)!==String(data.current_version)?`${current} → v${data.latest_version}`:current;
    if(status)status.textContent=data.error||data.message||(data.status==='up_to_date'?'Bạn đang dùng bản mới nhất.':data.status==='no_release'?'Chưa có bản phát hành mới.':'Sẵn sàng kiểm tra bản mới.');
    if(button){button.textContent=available?'Tải và cập nhật':'Kiểm tra cập nhật';button.classList.toggle('primary',Boolean(available));button.classList.toggle('secondary',!available);}
  };
  const load=async(check=false)=>{const button=$('#checkUpdate');if(check&&button){button.disabled=true;button.textContent='Đang kiểm tra…';}try{const data=await api('/api/update'+(check?'?check=1':''));renderStatus(data);if(check)toast(data.message||'Đã kiểm tra cập nhật');return data;}catch(error){if($('#updateStatus'))$('#updateStatus').textContent=error.message;if(check)toast(error.message);return null;}finally{if(button)button.disabled=false;}};
  const autoCheck=async()=>{const last=Number(localStorage.getItem('novel-update-check')||0);if(Date.now()-last<6*60*60*1000)return;localStorage.setItem('novel-update-check',String(Date.now()));try{renderStatus(await api('/api/update?check=1'));}catch(_error){}};
  const renderWhatsNew=(entry)=>{$('#whatsNewVersion').textContent=`v${entry.version}${entry.date?` · ${entry.date}`:''}`;$('#whatsNewTitle').textContent=entry.title||'Có gì mới?';$('#whatsNewSummary').textContent=entry.summary||'Ứng dụng đã được cập nhật lên phiên bản mới.';const highlights=Array.isArray(entry.highlights)?entry.highlights.filter(Boolean):[];$('#whatsNewList').innerHTML=highlights.length?highlights.map(item=>`<div class="whats-new-item"><span class="ui-icon ui-icon-check" aria-hidden="true"></span><p>${escapeHtml(item)}</p></div>`).join(''):'<div class="whats-new-empty">Chưa có ghi chú chi tiết cho phiên bản này.</div>';};
  const loadWhatsNew=async(force=false)=>{try{const [update,notes,launcher]=await Promise.all([api('/api/update'),api('/release-notes.json'),api('/api/launcher')]),versions=Array.isArray(notes.versions)?notes.versions:[];const entry=versions.find(item=>String(item.version)===String(update.current_version))||{version:update.current_version,title:`Aiko App Translator ${update.current_version}`,summary:'Ứng dụng đã được cập nhật lên phiên bản mới.',highlights:[]};whatsNew=entry;renderWhatsNew(entry);const needsLauncher=Boolean(launcher.available&&!launcher.configured);$('#launcherOnboarding').hidden=!needsLauncher;const seen=localStorage.getItem('novel-whats-new-version');if(force||needsLauncher||seen!==String(entry.version)){$('#whatsNewModal').classList.add('open');requestAnimationFrame(()=>(needsLauncher?$('#openLauncherOnboarding'):$('#closeWhatsNew')).focus());}}catch(error){if(force)toast(error.message);}};
  const closeWhatsNew=()=>{if(whatsNew?.version)localStorage.setItem('novel-whats-new-version',String(whatsNew.version));$('#whatsNewModal').classList.remove('open');};
  const finishInstall=async()=>{if(installing)return;installing=true;clearInterval(pollTimer);try{const result=await api('/api/update/install',{method:'POST',body:'{}'});$('#updateStatus').textContent='Đã tải và xác minh. Aiko đang khởi động lại để cài đặt.';$('#checkUpdate').textContent='Đang khởi động lại…';$('#cancelUpdate').hidden=true;toast(result.message);}catch(error){installing=false;$('#checkUpdate').disabled=false;$('#checkUpdate').textContent='Thử cài đặt lại';$('#updateStatus').textContent=error.message;toast(error.message);}};
  const renderProgress=(data)=>{const box=$('#updateProgress'),bar=$('#updateProgressBar'),detail=$('#updateProgressDetail'),button=$('#checkUpdate'),cancel=$('#cancelUpdate');box.hidden=false;const known=Number.isFinite(Number(data.percent));box.classList.toggle('indeterminate',!known);bar.style.width=known?`${Math.min(100,Number(data.percent))}%`:'';cancel.hidden=!['preparing','downloading','ready'].includes(data.stage);if(data.stage==='preparing'){detail.textContent='Đang chuẩn bị tải…';return;}if(data.stage==='downloading'){const total=data.total?` / ${formatBytes(data.total)}`:'';const percent=known?` · ${Number(data.percent).toFixed(1)}%`:'';const speed=data.speed?` · ${formatBytes(data.speed)}/s`:'';const eta=data.eta!=null?` · còn khoảng ${formatTime(data.eta)}`:'';detail.textContent=`${formatBytes(data.downloaded)}${total}${percent}${speed}${eta}`;return;}if(data.stage==='ready'){detail.textContent='Đã tải xong và xác minh an toàn.';finishInstall();return;}if(data.stage==='cancelled'){clearInterval(pollTimer);detail.textContent='Đã hủy tải bản cập nhật.';button.disabled=false;button.textContent='Tải và cập nhật';cancel.hidden=true;return;}if(data.stage==='error'){clearInterval(pollTimer);detail.textContent=data.error||'Không thể tải bản cập nhật.';$('#updateStatus').textContent=detail.textContent;button.disabled=false;button.textContent='Thử lại';cancel.hidden=true;}};
  const pollProgress=async()=>{try{renderProgress(await api('/api/update/progress'));}catch(error){clearInterval(pollTimer);toast(error.message);}};
  const install=async()=>{if(hasUnsavedChanges())return toast('Hãy lưu thay đổi đang soạn trước khi cập nhật');if(!available)return load(true);if(!confirm(`Tải và cập nhật lên phiên bản ${available.latest_version}? Aiko sẽ tự khởi động lại sau khi tải xong.`))return;const button=$('#checkUpdate');button.disabled=true;button.textContent='Đang tải bản cập nhật…';installing=false;try{await api('/api/update',{method:'POST',body:'{}'});await pollProgress();clearInterval(pollTimer);pollTimer=setInterval(pollProgress,500);}catch(error){button.disabled=false;button.textContent='Tải và cập nhật';$('#updateStatus').textContent=error.message;toast(error.message);}};
  const cancelDownload=async()=>{const button=$('#cancelUpdate');button.disabled=true;try{await api('/api/update/cancel',{method:'POST',body:'{}'});$('#updateStatus').textContent='Đang hủy tải bản cập nhật…';}catch(error){toast(error.message);}finally{button.disabled=false;}};
  const openLauncher=async()=>{const button=$('#openLauncherOnboarding');button.disabled=true;button.textContent='Đang mở…';try{const result=await api('/api/launcher/open',{method:'POST',body:'{}'});$('#launcherOnboarding').hidden=true;toast(result.message);}catch(error){button.disabled=false;button.textContent='Mở launcher ngay';toast(error.message);}};
  const bind=()=>{const check=$('#checkUpdate'),notes=$('#showWhatsNew'),close=$('#closeWhatsNew'),launcher=$('#openLauncherOnboarding'),cancel=$('#cancelUpdate'),progress=$('#updateProgress');const card=document.querySelector('.update-card'),actions=card?.querySelector('.update-actions'),info=card?.firstElementChild;if(progress&&info)info.appendChild(progress);if(cancel&&actions){actions.appendChild(cancel);if(check)actions.appendChild(check);}resetProgress();if(check)check.onclick=()=>available?install():load(true);if(notes)notes.onclick=()=>loadWhatsNew(true);if(close)close.onclick=closeWhatsNew;if(launcher)launcher.onclick=openLauncher;if(cancel)cancel.onclick=cancelDownload;};
  return {autoCheck,bind,closeWhatsNew,load,loadWhatsNew};
}
