"""Declarative schema for application settings and sidebar preferences."""

DEFAULT_R19_MODEL = "gemini-3.5-flash-lite"

DEFAULT_PINNED_SIDEBAR = [
    "workspace", "chapters", "pipeline", "terminology", "characters", "help",
]
SIDEBAR_FEATURES = set(DEFAULT_PINNED_SIDEBAR) | {
    "sharing", "hakoEdit", "pronouns", "r19", "ai-log", "settings",
}
FIXED_SIDEBAR_FEATURES = {"settings"}

DEFAULT_REVIEW_BG_CRITERIA = """1. Thiếu nội dung: chỉ báo khi một ý, hành động, hội thoại hoặc sự kiện trong bản gốc thực sự biến mất khỏi bản dịch; không báo lỗi khi bản dịch diễn đạt cô đọng nhưng vẫn đủ nghĩa.
2. Dịch sai nội dung: báo khi ý nghĩa thay đổi rõ rệt, nhầm nhân vật, sự kiện hoặc quan hệ nguyên nhân-kết quả.
3. Xưng hô: kiểm tra giới tính, vai vế, quan hệ và ngữ cảnh giao tiếp của nhân vật.
4. Phong cách và thuật ngữ: kiểm tra độ tự nhiên của tiếng Việt và tính nhất quán với glossary tham chiếu.
5. Ngoại ngữ: chỉ báo khi ký tự hoặc câu ngoại ngữ thực sự còn xuất hiện trong bản dịch; không dùng văn bản nguồn làm bằng chứng cho lỗi này.
6. Chỉ nêu lỗi khi có dẫn chứng cụ thể trong cả bản gốc và bản dịch; không suy đoán hoặc bắt lỗi khác biệt diễn đạt thuần túy."""
SETTING_DEFAULTS = {
    "pipeline_translate_provider": "gemini-api",
    "pipeline_translate_model": "gemini-3.5-flash",
    "pipeline_translate_thinking": "high",
    "pipeline_polish_provider": "gemini-api",
    "pipeline_polish_model": "gemini-3-flash-preview",
    "pipeline_polish_thinking": "high",
    "pipeline_pronouns_provider": "gemini-api",
    "pipeline_pronouns_model": "gemini-3.1-flash-lite-preview",
    "pipeline_pronouns_thinking": "high",
    "pipeline_review_provider": "gemini-api",
    "pipeline_review_model": "gemini-3.1-flash-lite-preview",
    "pipeline_review_thinking": "high",
    "pipeline_context_provider": "gemini-api",
    "pipeline_context_model": "gemini-3.5-flash",
    "pipeline_context_thinking": "high",
    "pipeline_characters_provider": "gemini-api",
    "pipeline_characters_model": "gemini-3.5-flash",
    "pipeline_characters_thinking": "high",
    "link_gemini": "https://gemini.google.com/gem/fdec65ac9c69",
    "translate_model": "gemini-3.5-flash",
    "r19_model": DEFAULT_R19_MODEL,
    "polish_model": "gemini-3-flash-preview",
    "review_bg_model": "gemini-3.1-flash-lite-preview",
    "review_bg_criteria": DEFAULT_REVIEW_BG_CRITERIA,
    "pronoun_model": "gemini-3.1-flash-lite-preview",
    "review_model": "gemini-3.1-flash-lite-preview",
    "context_model": "gemini-3.5-flash",
    "gemini_api_thinking": "high",
    "gemini_api_max_output_tokens": "",
    "gemini_api_streaming": "off",
    "gemini_web_model": "pro",
    "gemini_thinking": "extended",
    "link_chatgpt": "https://chatgpt.com/",
    "chatgpt_model": "gpt-5.6 sol",
    "chatgpt_thinking": "cao",
    "fix_max_retry": 3,
    "previous_context_chapters": 3,
    "hako_username": "",
    "hako_password": "",
    "hako_management_url": "",
    "r2_account_id": "",
    "r2_access_key_id": "",
    "r2_secret_access_key": "",
    "r2_bucket": "",
    "r2_public_url": "",
    "share_r2_account_id": "",
    "share_r2_access_key_id": "",
    "share_r2_secret_access_key": "",
    "share_r2_bucket": "private-shares",
    "share_worker_url": "",
    "gpt_api_key": "",
    "gpt_api_endpoint": "https://api.openai.com/v1/responses",
    "gpt_api_translate_model": "gpt-5.6-luna",
    "gpt_api_polish_model": "gpt-5.6-terra",
    "gpt_api_pronoun_model": "gpt-5.6-terra",
    "gpt_api_review_model": "gpt-5.6-terra",
    "gpt_api_translate_effort": "medium",
    "gpt_api_polish_effort": "high",
    "gpt_api_review_effort": "high",
    "gpt_api_max_output_tokens": 30000,
    "gpt_api_timeout": 300,
    "gpt_api_retries": 3,
    "gpt_api_temperature": "",
    "lan_enabled": "off",
    "lan_pin": "",
}
SETTING_LABELS = {
    "pipeline_translate_provider": "Provider dịch",
    "pipeline_translate_model": "Model",
    "pipeline_translate_thinking": "Cấp độ suy nghĩ",
    "pipeline_polish_provider": "Provider hiệu đính",
    "pipeline_polish_model": "Model",
    "pipeline_polish_thinking": "Cấp độ suy nghĩ",
    "pipeline_pronouns_provider": "Provider xưng hô",
    "pipeline_pronouns_model": "Model",
    "pipeline_pronouns_thinking": "Cấp độ suy nghĩ",
    "pipeline_review_provider": "Provider review",
    "pipeline_review_model": "Model",
    "pipeline_review_thinking": "Cấp độ suy nghĩ",
    "pipeline_context_provider": "Provider tạo Context",
    "pipeline_context_model": "Model",
    "pipeline_context_thinking": "Cấp độ suy nghĩ",
    "pipeline_characters_provider": "Provider hồ sơ nhân vật",
    "pipeline_characters_model": "Model",
    "pipeline_characters_thinking": "Cấp độ suy nghĩ",
    "link_gemini": "Đường dẫn Gemini Gem",
    "translate_model": "Model dịch Gemini API",
    "r19_model": "Model Gemini API dịch từ R19",
    "polish_model": "Model hậu dịch",
    "review_bg_model": "Model review chạy nền",
    "review_bg_criteria": "Tiêu chí review nền",
    "pronoun_model": "Model cập nhật xưng hô",
    "review_model": "Model review toàn bộ",
    "context_model": "Model tạo context",
    "gemini_api_thinking": "Cấp độ suy nghĩ",
    "gemini_api_max_output_tokens": "Token đầu ra tối đa",
    "gemini_api_streaming": "Streaming thử nghiệm",
    "gemini_web_model": "Model Gemini Web (flash/pro/thinking)",
    "gemini_thinking": "Mức thinking Gemini Web",
    "link_chatgpt": "Đường dẫn cuộc chat ChatGPT",
    "chatgpt_model": "Model ChatGPT Web mặc định",
    "chatgpt_thinking": "Thinking ChatGPT Web mặc định",
    "fix_max_retry": "Số lần sửa ký tự ngoại ngữ",
    "previous_context_chapters": "Số chương trước làm ngữ cảnh dịch",
    "hako_username": "Tên đăng nhập Hako",
    "hako_password": "Mật khẩu Hako",
    "hako_management_url": "Đường dẫn tạo chương Hako",
    "r2_account_id": "R2 Account ID",
    "r2_access_key_id": "R2 Access Key ID",
    "r2_secret_access_key": "R2 Secret Access Key",
    "r2_bucket": "Tên bucket R2",
    "r2_public_url": "Đường dẫn public R2",
    "share_r2_account_id": "Share R2 Account ID",
    "share_r2_access_key_id": "Share R2 Access Key ID",
    "share_r2_secret_access_key": "Share R2 Secret Access Key",
    "share_r2_bucket": "Tên bucket share private",
    "share_worker_url": "Đường dẫn Share Worker",
    "gpt_api_key": "OpenAI API key",
    "gpt_api_endpoint": "Endpoint GPT Responses API",
    "gpt_api_translate_model": "Model OpenAI API dùng để dịch",
    "gpt_api_polish_model": "Model OpenAI API dùng để hiệu đính",
    "gpt_api_pronoun_model": "Model OpenAI API cập nhật xưng hô",
    "gpt_api_review_model": "Model OpenAI API dùng để review",
    "gpt_api_translate_effort": "Reasoning effort khi dịch",
    "gpt_api_polish_effort": "Reasoning effort khi hiệu đính",
    "gpt_api_review_effort": "Reasoning effort khi review",
    "gpt_api_max_output_tokens": "Số token đầu ra tối đa GPT API",
    "gpt_api_timeout": "Thời gian chờ GPT API (giây)",
    "gpt_api_retries": "Số lần thử lại GPT API",
    "gpt_api_temperature": "Temperature GPT API (để trống = mặc định)",
    "lan_enabled": "Truy cập từ điện thoại cùng Wi-Fi",
    "lan_pin": "Mã PIN truy cập LAN",
}
SECRET_SETTINGS = {"hako_password", "r2_access_key_id", "r2_secret_access_key", "share_r2_access_key_id", "share_r2_secret_access_key", "gpt_api_key", "lan_pin"}
SETTING_RANGES = {
    "fix_max_retry": (1, 20),
    "previous_context_chapters": (0, 20),
    "gpt_api_max_output_tokens": (1000, 128000),
    "gpt_api_timeout": (30, 3600),
    "gpt_api_retries": (1, 10),
}
SETTING_META = {
    "pipeline_translate_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"]]},
    "pipeline_translate_model": {"group": "pipeline"},
    "pipeline_translate_thinking": {"group": "pipeline"},
    "pipeline_polish_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"], ["off", "Tắt"]]},
    "pipeline_polish_model": {"group": "pipeline"},
    "pipeline_polish_thinking": {"group": "pipeline"},
    "pipeline_pronouns_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"], ["off", "Tắt"]]},
    "pipeline_pronouns_model": {"group": "pipeline"},
    "pipeline_pronouns_thinking": {"group": "pipeline"},
    "pipeline_review_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"], ["off", "Tắt"]]},
    "pipeline_review_model": {"group": "pipeline"},
    "pipeline_review_thinking": {"group": "pipeline"},
    "pipeline_context_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"]]},
    "pipeline_context_model": {"group": "pipeline"},
    "pipeline_context_thinking": {"group": "pipeline"},
    "pipeline_characters_provider": {"group": "pipeline", "type": "select", "options": [["gemini-api", "Gemini API"], ["gemini-web", "Gemini Web"], ["openai-api", "OpenAI API"], ["chatgpt-web", "ChatGPT Web"]]},
    "pipeline_characters_model": {"group": "pipeline"},
    "pipeline_characters_thinking": {"group": "pipeline"},
    "link_gemini": {"group": "gemini-web"},
    "translate_model": {"group": "gemini-api", "description": "Model dùng cho bản dịch chính."},
    "r19_model": {"group": "gemini-api", "description": "Model API riêng dùng để dịch từng từ/cụm R19 chưa có trong cache."},
    "polish_model": {"group": "gemini-api", "description": "Model biên tập sau khi dịch. Để trống hoặc nhập none để bỏ qua."},
    "review_bg_model": {"group": "gemini-api", "description": "Model review nhanh chạy nền. Để trống hoặc nhập none để bỏ qua."},
    "review_bg_criteria": {"group": "general", "type": "textarea", "description": "Các tiêu chí được chèn trực tiếp vào prompt review từng chương."},
    "pronoun_model": {"group": "gemini-api", "description": "Model trích xuất và cập nhật pronouns.json. Để trống hoặc nhập none để bỏ qua."},
    "review_model": {"group": "gemini-api", "description": "Model dùng khi review toàn bộ truyện. Để trống hoặc nhập none để bỏ qua."},
    "context_model": {"group": "gemini-api", "description": "Model Gemini API dùng để tạo glossary.txt. Để trống hoặc nhập none để bỏ qua."},
    "gemini_api_thinking": {"group": "gemini-api", "type": "select", "options": [
        ["auto", "Tự động theo model"], ["off", "Tắt"], ["minimal", "Minimal"],
        ["low", "Low"], ["medium", "Medium"], ["high", "High"],
    ], "description": "Model không hỗ trợ một mức cụ thể có thể trả lỗi; khi đó chọn Tự động."},
    "gemini_api_max_output_tokens": {"group": "gemini-api", "inputmode": "numeric", "description": "Để trống để dùng giới hạn của model."},
    "gemini_api_streaming": {"group": "gemini-api", "type": "select", "options": [["off", "Tắt"], ["on", "Bật"]], "description": "Hiển thị bản dịch trực tiếp trong editor qua Gemini Interactions. Một số tùy chọn API có thể không được áp dụng."},
    "gemini_web_model": {"group": "gemini-web"},
    "gemini_thinking": {"group": "gemini-web"},
    "link_chatgpt": {"group": "chatgpt-web"},
    "chatgpt_model": {"group": "chatgpt-web"},
    "chatgpt_thinking": {"group": "chatgpt-web"},
    "fix_max_retry": {"group": "general"},
    "previous_context_chapters": {"group": "general", "description": "Số bản dịch liền trước được đưa vào prompt. Mặc định: 3."},
    "hako_username": {"group": "publishing"}, "hako_password": {"group": "publishing"},
    "hako_management_url": {"group": "publishing"}, "r2_account_id": {"group": "publishing"},
    "r2_access_key_id": {"group": "publishing"}, "r2_secret_access_key": {"group": "publishing"},
    "r2_bucket": {"group": "publishing"}, "r2_public_url": {"group": "publishing"},
    "share_r2_account_id": {"group": "sharing"},
    "share_r2_access_key_id": {"group": "sharing"},
    "share_r2_secret_access_key": {"group": "sharing"},
    "share_r2_bucket": {"group": "sharing", "description": "Bucket private riêng; không bật r2.dev hoặc public domain."},
    "share_worker_url": {"group": "sharing", "description": "URL Worker đã bind bucket share, ví dụ https://aiko-share.example.workers.dev"},
    "gpt_api_key": {"group": "gpt-api"}, "gpt_api_endpoint": {"group": "gpt-api"},
    "gpt_api_translate_model": {"group": "gpt-api"},
    "gpt_api_polish_model": {"group": "gpt-api", "description": "Để trống hoặc nhập none để bỏ qua bước hiệu đính."},
    "gpt_api_pronoun_model": {"group": "gpt-api", "description": "Model trích xuất và cập nhật pronouns.json. Để trống hoặc nhập none để bỏ qua."},
    "gpt_api_review_model": {"group": "gpt-api"},
    "gpt_api_translate_effort": {"group": "gpt-api"}, "gpt_api_polish_effort": {"group": "gpt-api"},
    "gpt_api_review_effort": {"group": "gpt-api"},
    "gpt_api_max_output_tokens": {"group": "gpt-api"}, "gpt_api_timeout": {"group": "gpt-api"},
    "gpt_api_retries": {"group": "gpt-api"}, "gpt_api_temperature": {"group": "gpt-api"},
    "lan_enabled": {
        "group": "general",
        "type": "select",
        "options": [["off", "Tắt (chỉ máy tính này)"], ["on", "Bật trong mạng LAN"]],
        "description": "Cần khởi động lại app sau khi thay đổi.",
    },
    "lan_pin": {
        "group": "general",
        "inputmode": "numeric",
        "description": "6–12 chữ số. Để trống khi bật để app tự sinh mã 6 số.",
    },
}
OPTIONAL_SETTINGS = set(SETTING_DEFAULTS) - {
    "link_gemini", "translate_model", "r19_model", "gemini_web_model", "gemini_thinking",
    "link_chatgpt", "chatgpt_model", "chatgpt_thinking", "fix_max_retry",
    "gpt_api_endpoint", "gpt_api_translate_model",
    "gpt_api_translate_effort", "gpt_api_polish_effort",
}
HIDDEN_SETTINGS = {"r19_model", "review_model", "context_model"}
