"""Standalone LAN login page."""


LOGIN_HTML = """<!doctype html><html lang="vi"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Novel Translator Studio</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:20px;background:#101412;color:#e9efeb;font-family:Segoe UI,Arial,sans-serif}.card{width:min(100%,390px);padding:28px;border:1px solid #2b332f;border-radius:18px;background:#171c19;box-shadow:0 20px 70px #0008}.mark{display:grid;place-items:center;width:46px;height:46px;border-radius:13px;background:#d6f064;color:#18211e;font-size:22px;font-weight:800}h1{margin:22px 0 8px;font-size:24px}p{margin:0 0 22px;color:#a8b2ad;line-height:1.55}label{display:grid;gap:8px;font-size:13px;font-weight:700}input{width:100%;padding:14px;border:1px solid #36413b;border-radius:11px;background:#0f1311;color:#fff;font-size:20px;letter-spacing:.25em;text-align:center;outline:0}input:focus{border-color:#55b89d}button{width:100%;margin-top:14px;padding:13px;border:0;border-radius:11px;background:#177e68;color:#fff;font-weight:750}small{display:block;min-height:20px;margin-top:12px;color:#f08b7c;text-align:center}</style></head><body><main class="card"><div class="mark">N</div><h1>Truy cập từ điện thoại</h1><p>Nhập mã PIN đang hiển thị trong Cài đặt trên máy tính.</p><form><label>Mã PIN<input name="pin" inputmode="numeric" pattern="[0-9]{6,12}" maxlength="12" autocomplete="one-time-code" required></label><button>Đăng nhập</button><small></small></form></main><script>
const f=document.querySelector('form'),m=document.querySelector('small');f.onsubmit=async e=>{e.preventDefault();m.textContent='';const b=f.querySelector('button');b.disabled=true;try{const r=await fetch('/api/lan/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:new FormData(f).get('pin')})});const d=await r.json();if(!r.ok)throw Error(d.error||'Không đăng nhập được');location.reload()}catch(e){m.textContent=e.message}finally{b.disabled=false}};
</script></body></html>"""
